<a href="https://colab.research.google.com/github/dphi-official/Deep_Learning_Bootcamp/blob/master/Assignment_2/Getting_Started_Notebook_Intermediate_Assignment2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Please follow the below instructions to load the dataset in Notebook.**

## Download Data
We are given google drive link in the ‘Data’ section of problem page which has all the required train images (to build the model) and test data images for which one need to predict the labels (animal specie) of these images and submit the predictions on the DPhi platform.



We can use GoogleDriveDownloader from google_drive_downloader library in Python to download the shared files from the Google drive link: https://drive.google.com/file/d/176E-pLhoxTgWsJ3MeoJQV_GXczIA6g8D/view?usp=sharing

The file id in the above link is: 176E-pLhoxTgWsJ3MeoJQV_GXczIA6g8D

**Now we are all set to start the data science work!!!**

## Loading Libraries
Let's import the required libraries. Not importing all the libraries in one go instead we will be importing whenever we require one.

In [1]:
# import the basic libraries
import pandas as pd
import numpy as np
import tensorflow as tf
import os
import cv2

## Loading the Data


In [2]:
categories = {"elefante_train": "elefante", "farfalla_train": "farfalla", "mucca_train": "mucca", "pecora_train": "pecora", "scoiattolo_train": "scoiattolo"}
data=[]
animals=["elefante", "farfalla", "mucca",  "pecora", "scoiattolo"]
img_size=100      # Here we are taking image size as 100, but it's on you. You can take 50 or 40 or 32 and so on
def create_data():
        for category,translate in categories.items():
            path="animal_dataset_intermediate/train/"+category
            target=animals.index(translate)     # converting the categorical values to numbers - 0, 1, 2, 3, 4 denoting the animals in animals list
            
            for img in os.listdir(path):         # os.listdir gets you all the list of name of files located in the given path
                try:
                    img_array=cv2.imread(os.path.join(path,img),cv2.IMREAD_GRAYSCALE)    # converts the image to pixels and gray scales the images
                    new_img_array=cv2.resize(img_array,(img_size,img_size))              # resizing the images
                    data.append([new_img_array,target])                                  # appending the list of image pixels and respective target value (i.e. animal type) in data
                except Exception as e:
                    pass                                      # try and except is exception handling case in python, saves you from getting errors
                
            
create_data()

In [3]:
data   # data contains all the images pixel values and their respective labels

[[array([[122, 124, 125, ..., 123, 123, 121],
         [129, 130, 135, ..., 123, 124, 123],
         [125, 124, 137, ..., 125, 124, 124],
         ...,
         [123, 143, 145, ...,  88,  89,  72],
         [118, 128, 142, ...,  93,  82, 100],
         [127, 127, 119, ...,  87,  70, 108]], dtype=uint8),
  0],
 [array([[170, 171, 172, ..., 171, 172, 172],
         [170, 171, 172, ..., 172, 172, 171],
         [170, 171, 172, ..., 172, 172, 171],
         ...,
         [178, 174, 181, ..., 162, 163, 166],
         [178, 174, 170, ..., 163, 182, 166],
         [165, 148, 163, ..., 163, 160, 163]], dtype=uint8),
  0],
 [array([[178, 179, 178, ..., 185, 185, 183],
         [179, 179, 178, ..., 184, 184, 181],
         [177, 179, 180, ..., 185, 184, 183],
         ...,
         [120, 147, 161, ..., 153, 159, 162],
         [153, 167, 155, ..., 169, 153, 160],
         [147, 160, 154, ..., 166, 173, 170]], dtype=uint8),
  0],
 [array([[127, 144, 126, ..., 171, 162, 161],
         [134, 135, 1

In [4]:
# we can observe that there are 8196 number of images
print(len(data))

8196


In [5]:
print("One training example : ", data[0])
print("----------------------------------------------------")
print("image array : ", data[0][0])
print("----------------------------------------------------")
print("image array shape : ", data[0][0].shape)
print("----------------------------------------------------")
print("category label : ", data[0][1])

One training example :  [array([[122, 124, 125, ..., 123, 123, 121],
       [129, 130, 135, ..., 123, 124, 123],
       [125, 124, 137, ..., 125, 124, 124],
       ...,
       [123, 143, 145, ...,  88,  89,  72],
       [118, 128, 142, ...,  93,  82, 100],
       [127, 127, 119, ...,  87,  70, 108]], dtype=uint8), 0]
----------------------------------------------------
image array :  [[122 124 125 ... 123 123 121]
 [129 130 135 ... 123 124 123]
 [125 124 137 ... 125 124 124]
 ...
 [123 143 145 ...  88  89  72]
 [118 128 142 ...  93  82 100]
 [127 127 119 ...  87  70 108]]
----------------------------------------------------
image array shape :  (100, 100)
----------------------------------------------------
category label :  0


## Split the Data

In [25]:
X, y = [], []
for i in range(len(data)):
    X.append(data[i][0])
    y.append(data[i][1])

In [26]:
print("One training example's X [input image] : ", X[0])
print("----------------------------------------------------")
print("One training example's shape : ", X[0].shape)
print("----------------------------------------------------")
print("One training example's y [label/category] : ", y[0])

One training example's X [input image] :  [[122 124 125 ... 123 123 121]
 [129 130 135 ... 123 124 123]
 [125 124 137 ... 125 124 124]
 ...
 [123 143 145 ...  88  89  72]
 [118 128 142 ...  93  82 100]
 [127 127 119 ...  87  70 108]]
----------------------------------------------------
One training example's shape :  (100, 100)
----------------------------------------------------
One training example's y [label/category] :  0


In [37]:
X = np.array(X)
y = np.array(y)
y = pd.get_dummies(y)

In [38]:
# no. of training examples / batch size, height, width
print(X.shape)
print(y.shape)

(8196, 100, 100)
(8196, 5)


In [39]:
# Can split data using train_test_split

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 42, shuffle = True)

In [40]:
print("X train shape : ", X_train.shape)
print("y train shape : ", y_train.shape)
print("X test shape : ", X_test.shape)
print("y test shape : ", y_test.shape)

X train shape :  (5737, 100, 100)
y train shape :  (5737, 5)
X test shape :  (2459, 100, 100)
y test shape :  (2459, 5)


## Building Model


In [98]:
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense, Dropout, Flatten, Conv2D, MaxPool2D, BatchNormalization
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.models import load_model
import datetime

In [42]:
num_classes = len(animals)
print("animal classes : ", animals)

animal classes :  ['elefante', 'farfalla', 'mucca', 'pecora', 'scoiattolo']


In [59]:
# building a MLP

model1 = Sequential()
model1.add(Flatten(input_shape = (100, 100)))
model1.add(Dense(512, activation = 'relu', name = 'layer1'))
model1.add(Dropout(0.2))
model1.add(Dense(256, activation = 'relu', name = 'layer2'))
model1.add(Dropout(0.2))
model1.add(Dense(num_classes, activation = 'softmax'))

In [60]:
# summary of the model

model1.summary()

Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
flatten_1 (Flatten)          (None, 10000)             0         
_________________________________________________________________
layer1 (Dense)               (None, 512)               5120512   
_________________________________________________________________
dropout_6 (Dropout)          (None, 512)               0         
_________________________________________________________________
layer2 (Dense)               (None, 256)               131328    
_________________________________________________________________
dropout_7 (Dropout)          (None, 256)               0         
_________________________________________________________________
dense_3 (Dense)              (None, 5)                 1285      
Total params: 5,253,125
Trainable params: 5,253,125
Non-trainable params: 0
____________________________________________

In [61]:
# compiling the model
optimizer = Adam(learning_rate = 0.001)
model1.compile(loss = 'categorical_crossentropy', optimizer = optimizer, metrics = ['accuracy'])

In [62]:
%load_ext tensorboard

The tensorboard extension is already loaded. To reload it, use:
  %reload_ext tensorboard


In [63]:
# tensorboard visualization
path = "logs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorboard_callback = tf.keras.callbacks.TensorBoard(log_dir=path, histogram_freq=1)

In [65]:
# fitting the model on training data
model1.fit(X_train, y_train, epochs = 20, batch_size = 64, verbose = 1, callbacks=[tensorboard_callback])

Epoch 1/20
90/90 [==============================] - 2s 22ms/step - loss: 1.5975 - accuracy: 0.2285 0s - loss: 1.5974 
Epoch 2/20
90/90 [==============================] - 2s 22ms/step - loss: 1.5986 - accuracy: 0.2283
Epoch 3/20
90/90 [==============================] - 2s 22ms/step - loss: 1.5984 - accuracy: 0.2285
Epoch 4/20
90/90 [==============================] - 2s 22ms/step - loss: 1.5986 - accuracy: 0.2285
Epoch 5/20
90/90 [==============================] - 2s 22ms/step - loss: 1.6031 - accuracy: 0.2280
Epoch 6/20
90/90 [==============================] - 2s 22ms/step - loss: 1.6025 - accuracy: 0.2282
Epoch 7/20
90/90 [==============================] - 2s 22ms/step - loss: 1.5995 - accuracy: 0.2285
Epoch 8/20
90/90 [==============================] - 2s 22ms/step - loss: 1.5989 - accuracy: 0.2282
Epoch 9/20
90/90 [==============================] - 2s 22ms/step - loss: 1.5988 - accuracy: 0.2283
Epoch 10/20
90/90 [==============================] - 2s 22ms/step - loss: 1.5980 - accurac

In [66]:
%tensorboard --logdir logs/fit

Reusing TensorBoard on port 6006 (pid 13616), started 0:08:56 ago. (Use '!kill 13616' to kill it.)

## Optimize Model

In [89]:
# building a CNN model.
model2 = Sequential()
model2.add(Conv2D(filters = 32, kernel_size = (5, 5), activation = 'relu', input_shape = (100, 100, 1)))
model2.add(BatchNormalization())
model2.add(MaxPool2D(pool_size = (2, 2)))
model2.add(Dropout(0.2))

model2.add(Conv2D(filters = 64, kernel_size = (3, 3), activation = 'relu'))
model2.add(BatchNormalization())
model2.add(MaxPool2D(pool_size = (2, 2)))
model2.add(Dropout(0.2))

model2.add(Conv2D(filters = 128, kernel_size = (3, 3), activation = 'relu'))
model2.add(BatchNormalization())
model2.add(MaxPool2D(pool_size = (2, 2)))
model2.add(Dropout(0.2))

model2.add(Flatten())
model2.add(Dense(256, activation = 'relu'))
model2.add(BatchNormalization())
model2.add(Dropout(0.2))
model2.add(Dense(5, activation = "softmax"))

In [90]:
# summary of the CNN model

model2.summary()

Model: "sequential_11"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_15 (Conv2D)           (None, 96, 96, 32)        832       
_________________________________________________________________
batch_normalization_13 (Batc (None, 96, 96, 32)        128       
_________________________________________________________________
max_pooling2d_12 (MaxPooling (None, 48, 48, 32)        0         
_________________________________________________________________
dropout_21 (Dropout)         (None, 48, 48, 32)        0         
_________________________________________________________________
conv2d_16 (Conv2D)           (None, 46, 46, 64)        18496     
_________________________________________________________________
batch_normalization_14 (Batc (None, 46, 46, 64)        256       
_________________________________________________________________
max_pooling2d_13 (MaxPooling (None, 23, 23, 64)      

In [91]:
# compiling the CNN model
model2.compile(loss = 'categorical_crossentropy', optimizer = 'adam', metrics = ['accuracy'])

In [92]:
# tensorboard visualization
path = "logs/fit2/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorboard_callback_1 = tf.keras.callbacks.TensorBoard(log_dir=path, histogram_freq=1)

In [93]:
print(X_train.shape)
X_train = X_train.reshape(-1, 100, 100, 1)
print(X_train.shape)

(5737, 100, 100, 1)
(5737, 100, 100, 1)


In [95]:
# fitting the model on training data
model2.fit(X_train, y_train, epochs = 10, batch_size = 64, verbose = 1, callbacks=[tensorboard_callback_1])

Epoch 1/10
90/90 [==============================] - 118s 1s/step - loss: 0.9555 - accuracy: 0.6406
Epoch 2/10
90/90 [==============================] - 117s 1s/step - loss: 0.7653 - accuracy: 0.7101
Epoch 3/10
90/90 [==============================] - 115s 1s/step - loss: 0.6275 - accuracy: 0.7663
Epoch 4/10
90/90 [==============================] - 117s 1s/step - loss: 0.4968 - accuracy: 0.8126
Epoch 5/10
90/90 [==============================] - 118s 1s/step - loss: 0.3915 - accuracy: 0.8550
Epoch 6/10
90/90 [==============================] - 116s 1s/step - loss: 0.3281 - accuracy: 0.8841
Epoch 7/10
90/90 [==============================] - 117s 1s/step - loss: 0.2417 - accuracy: 0.9158
Epoch 8/10
90/90 [==============================] - 117s 1s/step - loss: 0.1805 - accuracy: 0.9372
Epoch 9/10
90/90 [==============================] - 117s 1s/step - loss: 0.1421 - accuracy: 0.9549
Epoch 10/10
90/90 [==============================] - 118s 1s/step - loss: 0.1186 - accuracy: 0.9634


In [102]:
%tensorboard --logdir logs/fit2

Reusing TensorBoard on port 6006 (pid 15648), started 0:00:56 ago. (Use '!kill 15648' to kill it.)

In [96]:
# lets save the CNN model.

model2.save('CNN_model.h5')

In [99]:
# lets load the saved model.

model = load_model('CNN_model.h5')

In [101]:
# printing the model summary
model.summary()

Model: "sequential_11"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_15 (Conv2D)           (None, 96, 96, 32)        832       
_________________________________________________________________
batch_normalization_13 (Batc (None, 96, 96, 32)        128       
_________________________________________________________________
max_pooling2d_12 (MaxPooling (None, 48, 48, 32)        0         
_________________________________________________________________
dropout_21 (Dropout)         (None, 48, 48, 32)        0         
_________________________________________________________________
conv2d_16 (Conv2D)           (None, 46, 46, 64)        18496     
_________________________________________________________________
batch_normalization_14 (Batc (None, 46, 46, 64)        256       
_________________________________________________________________
max_pooling2d_13 (MaxPooling (None, 23, 23, 64)      

# Loading the Test Data
We can load the test data similar to train_data

In [103]:
# Get the csv file given 'Testing_set_animals.csv'
test_image_ids = pd.read_csv("animal_dataset_intermediate/Testing_set_animals.csv")
test_image_ids.head()

filename  target
0  e030b20928e90021d85a5854ee454296eb70e3c818b413...     NaN
1  e030b20929e90021d85a5854ee454296eb70e3c818b413...     NaN
2  e030b2092be90021d85a5854ee454296eb70e3c818b413...     NaN
3  e030b2092ce90021d85a5854ee454296eb70e3c818b413...     NaN
4  e030b2092de90021d85a5854ee454296eb70e3c818b413...     NaN

In [108]:
test_image_ids.shape

(910, 2)

In [104]:
# Get image paths
image_paths = ['animal_dataset_intermediate/test/' + fname for fname in test_image_ids['filename']]
image_paths

['animal_dataset_intermediate/test/e030b20928e90021d85a5854ee454296eb70e3c818b413449df6c87ca3ed_640.jpg',
 'animal_dataset_intermediate/test/e030b20929e90021d85a5854ee454296eb70e3c818b413449df6c87ca3ed_640.jpg',
 'animal_dataset_intermediate/test/e030b2092be90021d85a5854ee454296eb70e3c818b413449df6c87ca3ed_640.jpg',
 'animal_dataset_intermediate/test/e030b2092ce90021d85a5854ee454296eb70e3c818b413449df6c87ca3ed_640.jpg',
 'animal_dataset_intermediate/test/e030b2092de90021d85a5854ee454296eb70e3c818b413449df6c87ca3ed_640.jpg',
 'animal_dataset_intermediate/test/e030b20a20e90021d85a5854ee454296eb70e3c818b413449df6c87ca3ed_640.jpg',
 'animal_dataset_intermediate/test/e032b10b2df21c22d2524518b7444f92e37fe5d404b0144390f8c07aa5ecb6_640.jpg',
 'animal_dataset_intermediate/test/e032b5082ef61c22d2524518b7444f92e37fe5d404b0144390f8c078a0eabd_640.jpg',
 'animal_dataset_intermediate/test/e034b80f2ff61c22d2524518b7444f92e37fe5d404b0144390f8c078a0eabd_640.jpg',
 'animal_dataset_intermediate/test/e037b

In [23]:
# Confirm if number of images is same as number of labels given


In [122]:
# Create dataframe of image ids and filepaths
test_data = pd.DataFrame({'filename': test_image_ids['filename'], 'filepath': image_paths })
print(test_data.shape)
test_data.head()
# this is completely optional to see if all the data images are in an order. You can skip this if you want

(910, 2)


filename  \
0  e030b20928e90021d85a5854ee454296eb70e3c818b413...   
1  e030b20929e90021d85a5854ee454296eb70e3c818b413...   
2  e030b2092be90021d85a5854ee454296eb70e3c818b413...   
3  e030b2092ce90021d85a5854ee454296eb70e3c818b413...   
4  e030b2092de90021d85a5854ee454296eb70e3c818b413...   

                                            filepath  
0  animal_dataset_intermediate/test/e030b20928e90...  
1  animal_dataset_intermediate/test/e030b20929e90...  
2  animal_dataset_intermediate/test/e030b2092be90...  
3  animal_dataset_intermediate/test/e030b2092ce90...  
4  animal_dataset_intermediate/test/e030b2092de90...

In [123]:
print(test_data['filepath'][1])
print(img_size)

animal_dataset_intermediate/test/e030b20929e90021d85a5854ee454296eb70e3c818b413449df6c87ca3ed_640.jpg
100


In [ ]:
img_array=cv2.imread(os.path.join(path,img),cv2.IMREAD_GRAYSCALE)    # converts the image to pixels and gray scales the images
                    new_img_array=cv2.resize(img_array,(img_size,img_size))

In [124]:
# Load image pixels using cv2
image_pixels = []
for i in range(test_data.shape[0]):
    img_array = cv2.imread(test_data['filepath'][i], cv2.IMREAD_GRAYSCALE)
    image_pixels.append(cv2.resize(img_array, (img_size, img_size)))

In [126]:
image_pixels = np.array(image_pixels)

In [127]:
image_pixels.shape

(910, 100, 100)

In [128]:
# lets bring it to the shape our model requires

image_pixels = image_pixels.reshape(-1, 100, 100, 1)
print(image_pixels.shape)

(910, 100, 100, 1)


## Prediction

In [129]:
# prediction
prediction = model.predict(image_pixels)

In [130]:
prediction.shape

(910, 5)

In [134]:
print(prediction[0])
print(np.argmax(prediction[0]))

[2.7314347e-04 7.7678300e-02 6.3024112e-04 3.1359044e-03 9.1828239e-01]
4


In [141]:
prediction = np.argmax(prediction, axis = 1)

In [144]:
print(prediction[0])
prediction[0:20]

4


array([4, 1, 1, 1, 1, 1, 0, 3, 4, 3, 0, 0, 0, 0, 4, 4, 0, 0, 2, 1],
      dtype=int64)

**Note: Follow the submission guidelines given in ‘[How To Submit](https://discuss.dphi.tech/t/how-to-submit-predictions/548)’ Section.**

# **How to save prediciton results locally via jupyter notebook?**
If you are working on Jupyter notebook, execute below block of codes. A file named ‘submission.csv’ will be created in your current working directory.

In [151]:
res = pd.DataFrame({'filename': test_data['filename'], 'animal_type': prediction})  # prediction is nothing but the final predictions of your model on input features of your new unseen test data
res.to_csv("submission.csv", index = False) 

In [153]:
check = pd.read_csv("submission.csv")
check.tail()

filename  animal_type
905  OIP-5ual0F5ZPZRdkGcj8uSH0AHaFj.jpeg            4
906  OIP-5VwIBS0B8SxZbUiAHBJg7gHaE8.jpeg            0
907  OIP-5WG0rHWAZYtu0utoZfuaAgHaFj.jpeg            0
908  OIP-5ZwfeYunG6CT2wEI7OjybQHaEo.jpeg            4
909  OIP-6A6SpPbz_YUI4ElMo-UhuQHaE8.jpeg            4

# **OR,**
**If you are working on Google Colab then use the below set of code to save prediction results locally**

# **How to save prediction results locally via colab notebook?**
If you are working on Google Colab Notebook, execute below block of codes. A file named ‘submission’ will be downloaded in your system.

In [ ]:
res = pd.DataFrame({'filename': test_data['filename'], 'animal_type': prediction})  # prediction is nothing but the final predictions of your model on input features of your new unseen test data
res.to_csv("submission.csv") 

# To download the csv file locally
from google.colab import files        
files.download('submission.csv')