<a href="https://colab.research.google.com/github/dphi-official/Deep_Learning_Bootcamp/blob/master/Assignment_2/Getting_Started_Notebook_Intermediate_Assignment2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Please follow the below instructions to load the dataset in Notebook.**

## Download Data
We are given google drive link in the ‘Data’ section of problem page which has all the required train images (to build the model) and test data images for which one need to predict the labels (animal specie) of these images and submit the predictions on the DPhi platform.



We can use GoogleDriveDownloader from google_drive_downloader library in Python to download the shared files from the Google drive link: https://drive.google.com/file/d/176E-pLhoxTgWsJ3MeoJQV_GXczIA6g8D/view?usp=sharing

The file id in the above link is: 176E-pLhoxTgWsJ3MeoJQV_GXczIA6g8D

**Now we are all set to start the data science work!!!**

## Loading Libraries
Let's import the required libraries. Not importing all the libraries in one go instead we will be importing whenever we require one.

In [1]:
# import the basic libraries
import pandas as pd
import numpy as np
import tensorflow as tf
import os
import cv2

## Loading the Data


In [2]:
categories = {"elefante_train": "elefante", "farfalla_train": "farfalla", "mucca_train": "mucca", "pecora_train": "pecora", "scoiattolo_train": "scoiattolo"}
data=[]
animals=["elefante", "farfalla", "mucca",  "pecora", "scoiattolo"]
img_size=100      # Here we are taking image size as 100, but it's on you. You can take 50 or 40 or 32 and so on
def create_data():
        for category,translate in categories.items():
            path="animal_dataset_intermediate/train/"+category
            target=animals.index(translate)     # converting the categorical values to numbers - 0, 1, 2, 3, 4 denoting the animals in animals list
            
            for img in os.listdir(path):         # os.listdir gets you all the list of name of files located in the given path
                try:
                    img_array=cv2.imread(os.path.join(path,img),cv2.IMREAD_GRAYSCALE)    # converts the image to pixels and gray scales the images
                    new_img_array=cv2.resize(img_array,(img_size,img_size))              # resizing the images
                    data.append([new_img_array,target])                                  # appending the list of image pixels and respective target value (i.e. animal type) in data
                except Exception as e:
                    pass                                      # try and except is exception handling case in python, saves you from getting errors
                
            
create_data()

In [3]:
#data   # data contains all the images pixel values and their respective labels

In [4]:
# we can observe that there are 8196 number of images
print(len(data))

8196


In [5]:
print("One training example : ", data[0])
print("----------------------------------------------------")
print("image array : ", data[0][0])
print("----------------------------------------------------")
print("image array shape : ", data[0][0].shape)
print("----------------------------------------------------")
print("category label : ", data[0][1])

One training example :  [array([[122, 124, 125, ..., 123, 123, 121],
       [129, 130, 135, ..., 123, 124, 123],
       [125, 124, 137, ..., 125, 124, 124],
       ...,
       [123, 143, 145, ...,  88,  89,  72],
       [118, 128, 142, ...,  93,  82, 100],
       [127, 127, 119, ...,  87,  70, 108]], dtype=uint8), 0]
----------------------------------------------------
image array :  [[122 124 125 ... 123 123 121]
 [129 130 135 ... 123 124 123]
 [125 124 137 ... 125 124 124]
 ...
 [123 143 145 ...  88  89  72]
 [118 128 142 ...  93  82 100]
 [127 127 119 ...  87  70 108]]
----------------------------------------------------
image array shape :  (100, 100)
----------------------------------------------------
category label :  0


## Split the Data

In [6]:
X, y = [], []
for i in range(len(data)):
    X.append(data[i][0])
    y.append(data[i][1])

In [7]:
print("One training example's X [input image] : ", X[0])
print("----------------------------------------------------")
print("One training example's shape : ", X[0].shape)
print("----------------------------------------------------")
print("One training example's y [label/category] : ", y[0])

One training example's X [input image] :  [[122 124 125 ... 123 123 121]
 [129 130 135 ... 123 124 123]
 [125 124 137 ... 125 124 124]
 ...
 [123 143 145 ...  88  89  72]
 [118 128 142 ...  93  82 100]
 [127 127 119 ...  87  70 108]]
----------------------------------------------------
One training example's shape :  (100, 100)
----------------------------------------------------
One training example's y [label/category] :  0


In [8]:
X = np.array(X)
y = np.array(y)
y = pd.get_dummies(y)

In [9]:
# no. of training examples / batch size, height, width
print(X.shape)
print(y.shape)

(8196, 100, 100)
(8196, 5)


In [10]:
# Can split data using train_test_split

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 42, shuffle = True)

In [11]:
print("X train shape : ", X_train.shape)
print("y train shape : ", y_train.shape)
print("X test shape : ", X_test.shape)
print("y test shape : ", y_test.shape)

X train shape :  (5737, 100, 100)
y train shape :  (5737, 5)
X test shape :  (2459, 100, 100)
y test shape :  (2459, 5)


## Building Model


In [12]:
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense, Dropout, Flatten, Conv2D, MaxPool2D, BatchNormalization
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.models import load_model
import datetime

In [13]:
num_classes = len(animals)
print("animal classes : ", animals)

animal classes :  ['elefante', 'farfalla', 'mucca', 'pecora', 'scoiattolo']


In [14]:
# building a MLP

model1 = Sequential()
model1.add(Flatten(input_shape = (100, 100)))
model1.add(Dense(512, activation = 'relu', name = 'layer1'))
model1.add(Dropout(0.2))
model1.add(Dense(256, activation = 'relu', name = 'layer2'))
model1.add(Dropout(0.2))
model1.add(Dense(num_classes, activation = 'softmax'))

In [15]:
# summary of the model

model1.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
flatten (Flatten)            (None, 10000)             0         
_________________________________________________________________
layer1 (Dense)               (None, 512)               5120512   
_________________________________________________________________
dropout (Dropout)            (None, 512)               0         
_________________________________________________________________
layer2 (Dense)               (None, 256)               131328    
_________________________________________________________________
dropout_1 (Dropout)          (None, 256)               0         
_________________________________________________________________
dense (Dense)                (None, 5)                 1285      
Total params: 5,253,125
Trainable params: 5,253,125
Non-trainable params: 0
______________________________________________

In [16]:
# compiling the model
optimizer = Adam(learning_rate = 0.001)
model1.compile(loss = 'categorical_crossentropy', optimizer = optimizer, metrics = ['accuracy'])

In [17]:
%load_ext tensorboard

In [18]:
# tensorboard visualization
path = "logs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorboard_callback = tf.keras.callbacks.TensorBoard(log_dir=path, histogram_freq=1)

In [19]:
# fitting the model on training data
model1.fit(X_train, y_train, epochs = 20, batch_size = 64, verbose = 1, callbacks=[tensorboard_callback])

Epoch 1/20
 1/90 [..............................] - ETA: 0s - loss: 265.4891 - accuracy: 0.1094WARNING:tensorflow:From C:\Users\vinee\anaconda3\lib\site-packages\tensorflow\python\ops\summary_ops_v2.py:1277: stop (from tensorflow.python.eager.profiler) is deprecated and will be removed after 2020-07-01.
Instructions for updating:
use `tf.profiler.experimental.stop` instead.
90/90 [==============================] - 3s 38ms/step - loss: 324.3684 - accuracy: 0.2144
Epoch 2/20
90/90 [==============================] - 3s 34ms/step - loss: 1.6515 - accuracy: 0.2074
Epoch 3/20
90/90 [==============================] - 3s 35ms/step - loss: 1.6077 - accuracy: 0.2210
Epoch 4/20
90/90 [==============================] - 3s 35ms/step - loss: 1.5970 - accuracy: 0.2278
Epoch 5/20
90/90 [==============================] - 3s 34ms/step - loss: 1.6018 - accuracy: 0.2280
Epoch 6/20
90/90 [==============================] - 3s 33ms/step - loss: 1.6057 - accuracy: 0.2278 0s - loss: 1.6058 - accuracy: 0.
Epoch

In [20]:
%tensorboard --logdir logs/fit

Reusing TensorBoard on port 6006 (pid 13616), started 4:26:23 ago. (Use '!kill 13616' to kill it.)

## Optimize Model

In [21]:
# building a CNN model.
model2 = Sequential()
model2.add(Conv2D(filters = 32, kernel_size = (5, 5), activation = 'relu', input_shape = (100, 100, 1)))
model2.add(BatchNormalization())
model2.add(MaxPool2D(pool_size = (2, 2)))
model2.add(Dropout(0.2))

model2.add(Conv2D(filters = 64, kernel_size = (3, 3), activation = 'relu'))
model2.add(BatchNormalization())
model2.add(MaxPool2D(pool_size = (2, 2)))
model2.add(Dropout(0.2))

model2.add(Conv2D(filters = 128, kernel_size = (3, 3), activation = 'relu'))
model2.add(BatchNormalization())
model2.add(MaxPool2D(pool_size = (2, 2)))
model2.add(Dropout(0.2))

model2.add(Flatten())
model2.add(Dense(256, activation = 'relu'))
model2.add(BatchNormalization())
model2.add(Dropout(0.2))
model2.add(Dense(5, activation = "softmax"))

In [22]:
# summary of the CNN model

model2.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d (Conv2D)              (None, 96, 96, 32)        832       
_________________________________________________________________
batch_normalization (BatchNo (None, 96, 96, 32)        128       
_________________________________________________________________
max_pooling2d (MaxPooling2D) (None, 48, 48, 32)        0         
_________________________________________________________________
dropout_2 (Dropout)          (None, 48, 48, 32)        0         
_________________________________________________________________
conv2d_1 (Conv2D)            (None, 46, 46, 64)        18496     
_________________________________________________________________
batch_normalization_1 (Batch (None, 46, 46, 64)        256       
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 23, 23, 64)       

In [23]:
# compiling the CNN model
model2.compile(loss = 'categorical_crossentropy', optimizer = 'adam', metrics = ['accuracy'])

In [24]:
# tensorboard visualization
path = "logs/fit2/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorboard_callback_1 = tf.keras.callbacks.TensorBoard(log_dir=path, histogram_freq=1)

In [25]:
print(X_train.shape)
X_train = X_train.reshape(-1, 100, 100, 1)
print(X_train.shape)

(5737, 100, 100)
(5737, 100, 100, 1)


In [26]:
# fitting the model on training data
model2.fit(X_train, y_train, epochs = 15, batch_size = 64, verbose = 1, callbacks=[tensorboard_callback_1])

Epoch 1/15
90/90 [==============================] - 74s 826ms/step - loss: 1.3780 - accuracy: 0.4851
Epoch 2/15
90/90 [==============================] - 73s 815ms/step - loss: 0.9449 - accuracy: 0.6408
Epoch 3/15
90/90 [==============================] - 74s 818ms/step - loss: 0.7670 - accuracy: 0.7072
Epoch 4/15
90/90 [==============================] - 73s 813ms/step - loss: 0.6556 - accuracy: 0.7534
Epoch 5/15
90/90 [==============================] - 75s 833ms/step - loss: 0.5315 - accuracy: 0.8023
Epoch 6/15
90/90 [==============================] - 75s 830ms/step - loss: 0.4246 - accuracy: 0.8524
Epoch 7/15
90/90 [==============================] - 74s 817ms/step - loss: 0.3220 - accuracy: 0.8830
Epoch 8/15
90/90 [==============================] - 79s 873ms/step - loss: 0.2562 - accuracy: 0.9125
Epoch 9/15
90/90 [==============================] - 116s 1s/step - loss: 0.1929 - accuracy: 0.9338
Epoch 10/15
90/90 [==============================] - 116s 1s/step - loss: 0.1500 - accuracy: 

In [27]:
%tensorboard --logdir logs/fit2

Reusing TensorBoard on port 6006 (pid 15648), started 3:49:03 ago. (Use '!kill 15648' to kill it.)

In [28]:
# lets save the CNN model.

model2.save('CNN_model_01.h5')

In [29]:
# lets load the saved model.

model = load_model('CNN_model_01.h5')

In [30]:
# printing the model summary
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d (Conv2D)              (None, 96, 96, 32)        832       
_________________________________________________________________
batch_normalization (BatchNo (None, 96, 96, 32)        128       
_________________________________________________________________
max_pooling2d (MaxPooling2D) (None, 48, 48, 32)        0         
_________________________________________________________________
dropout_2 (Dropout)          (None, 48, 48, 32)        0         
_________________________________________________________________
conv2d_1 (Conv2D)            (None, 46, 46, 64)        18496     
_________________________________________________________________
batch_normalization_1 (Batch (None, 46, 46, 64)        256       
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 23, 23, 64)       

# Loading the Test Data
We can load the test data similar to train_data

In [31]:
# Get the csv file given 'Testing_set_animals.csv'
test_image_ids = pd.read_csv("animal_dataset_intermediate/Testing_set_animals.csv")
test_image_ids.head()

filename  target
0  e030b20928e90021d85a5854ee454296eb70e3c818b413...     NaN
1  e030b20929e90021d85a5854ee454296eb70e3c818b413...     NaN
2  e030b2092be90021d85a5854ee454296eb70e3c818b413...     NaN
3  e030b2092ce90021d85a5854ee454296eb70e3c818b413...     NaN
4  e030b2092de90021d85a5854ee454296eb70e3c818b413...     NaN

In [32]:
test_image_ids.shape

(910, 2)

In [33]:
# Get image paths
image_paths = ['animal_dataset_intermediate/test/' + fname for fname in test_image_ids['filename']]
image_paths[0]

'animal_dataset_intermediate/test/e030b20928e90021d85a5854ee454296eb70e3c818b413449df6c87ca3ed_640.jpg'

In [34]:
# Create dataframe of image ids and filepaths
test_data = pd.DataFrame({'filename': test_image_ids['filename'], 'filepath': image_paths })
print(test_data.shape)
test_data.head()
# this is completely optional to see if all the data images are in an order. You can skip this if you want

(910, 2)


filename  \
0  e030b20928e90021d85a5854ee454296eb70e3c818b413...   
1  e030b20929e90021d85a5854ee454296eb70e3c818b413...   
2  e030b2092be90021d85a5854ee454296eb70e3c818b413...   
3  e030b2092ce90021d85a5854ee454296eb70e3c818b413...   
4  e030b2092de90021d85a5854ee454296eb70e3c818b413...   

                                            filepath  
0  animal_dataset_intermediate/test/e030b20928e90...  
1  animal_dataset_intermediate/test/e030b20929e90...  
2  animal_dataset_intermediate/test/e030b2092be90...  
3  animal_dataset_intermediate/test/e030b2092ce90...  
4  animal_dataset_intermediate/test/e030b2092de90...

In [123]:
print(test_data['filepath'][1])
print(img_size)

animal_dataset_intermediate/test/e030b20929e90021d85a5854ee454296eb70e3c818b413449df6c87ca3ed_640.jpg
100


In [35]:
# Load image pixels using cv2
image_pixels = []
for i in range(test_data.shape[0]):
    img_array = cv2.imread(test_data['filepath'][i], cv2.IMREAD_GRAYSCALE)
    image_pixels.append(cv2.resize(img_array, (img_size, img_size)))

In [36]:
image_pixels = np.array(image_pixels)

In [37]:
image_pixels.shape

(910, 100, 100)

In [38]:
# lets bring it to the shape our model requires

image_pixels = image_pixels.reshape(-1, 100, 100, 1)
print(image_pixels.shape)

(910, 100, 100, 1)


## Prediction

In [39]:
# prediction
prediction = model.predict(image_pixels)

In [40]:
prediction.shape

(910, 5)

In [41]:
print(prediction[0])
print(np.argmax(prediction[0]))

[9.8793025e-06 1.1330253e-02 1.7393626e-04 9.8835117e-01 1.3483877e-04]
3


In [42]:
prediction = np.argmax(prediction, axis = 1)

In [43]:
print(prediction[0])
prediction[0:20]

3


array([3, 3, 3, 1, 3, 3, 0, 3, 4, 4, 3, 0, 0, 1, 4, 1, 4, 0, 4, 3],
      dtype=int64)

**Note: Follow the submission guidelines given in ‘[How To Submit](https://discuss.dphi.tech/t/how-to-submit-predictions/548)’ Section.**

# **How to save prediciton results locally via jupyter notebook?**
If you are working on Jupyter notebook, execute below block of codes. A file named ‘submission.csv’ will be created in your current working directory.

In [44]:
res = pd.DataFrame({'filename': test_data['filename'], 'animal_type': prediction})  # prediction is nothing but the final predictions of your model on input features of your new unseen test data
res.to_csv("submission_01.csv", index = False) 

In [45]:
check = pd.read_csv("submission_01.csv")
check.tail()

filename  animal_type
905  OIP-5ual0F5ZPZRdkGcj8uSH0AHaFj.jpeg            4
906  OIP-5VwIBS0B8SxZbUiAHBJg7gHaE8.jpeg            3
907  OIP-5WG0rHWAZYtu0utoZfuaAgHaFj.jpeg            3
908  OIP-5ZwfeYunG6CT2wEI7OjybQHaEo.jpeg            4
909  OIP-6A6SpPbz_YUI4ElMo-UhuQHaE8.jpeg            4

# **OR,**
**If you are working on Google Colab then use the below set of code to save prediction results locally**

# **How to save prediction results locally via colab notebook?**
If you are working on Google Colab Notebook, execute below block of codes. A file named ‘submission’ will be downloaded in your system.

In [ ]:
res = pd.DataFrame({'filename': test_data['filename'], 'animal_type': prediction})  # prediction is nothing but the final predictions of your model on input features of your new unseen test data
res.to_csv("submission_01.csv") 

# To download the csv file locally
from google.colab import files        
files.download('submission_01.csv')